// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfrcaCfpoFV2jcF5ETzl82rp_LhFTR53Q',
    appId: '1:330173307223:web:db3951c9b536ee6c7a0612',
    messagingSenderId: '330173307223',
    projectId: 'fitnessapp-49cff',
    authDomain: 'fitnessapp-49cff.firebaseapp.com',
    storageBucket: 'fitnessapp-49cff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSMp82cix2pnaLtUIl0atdQRrOWuYNqhw',
    appId: '1:330173307223:android:2b635491bd8a90567a0612',
    messagingSenderId: '330173307223',
    projectId: 'fitnessapp-49cff',
    storageBucket: 'fitnessapp-49cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJZe2U0uP6ndhz50xsQTgj-3Nf2uhezwo',
    appId: '1:330173307223:ios:d10aceb78e26f90a7a0612',
    messagingSenderId: '330173307223',
    projectId: 'fitnessapp-49cff',
    storageBucket: 'fitnessapp-49cff.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJZe2U0uP6ndhz50xsQTgj-3Nf2uhezwo',
    appId: '1:330173307223:ios:d10aceb78e26f90a7a0612',
    messagingSenderId: '330173307223',
    projectId: 'fitnessapp-49cff',
    storageBucket: 'fitnessapp-49cff.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfrcaCfpoFV2jcF5ETzl82rp_LhFTR53Q',
    appId: '1:330173307223:web:926b8716238e56267a0612',
    messagingSenderId: '330173307223',
    projectId: 'fitnessapp-49cff',
    authDomain: 'fitnessapp-49cff.firebaseapp.com',
    storageBucket: 'fitnessapp-49cff.appspot.com',
  );
}
